<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Platforms>AnyCPU</Platforms>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Configurations>Debug;Release</Configurations>
    <Authors>heyitsleo;Fridtjof</Authors>
    <Company>NFSTools</Company>
    <Description>Library for reading and writing FNGs</Description>
    <Version>2.0.0-alpha</Version>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Keys\**\*.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>