<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net6.0</TargetFramework>
        <Platforms>AnyCPU</Platforms>
        <Configurations>Debug;Release</Configurations>
        <Authors>heyitsleo;Fridtjof</Authors>
        <Company>NFSTools</Company>
        <Description>CLI for de/recompiling FNG binary chunks</Description>
        <Version>0.2.0-alpha</Version>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="CommandLineParser" Version="2.8.0" />
      <PackageReference Include="JetBrains.Annotations" Version="2020.1.0" />
      <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
        <PackageReference Include="SixLabors.ImageSharp.Drawing" Version="1.0.0-beta11" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\FEngLib\FEngLib.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Update="compile_fng.bat">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="decompile_fng.bat">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>